
export const endpoints = {
    Auth: {
        signup: '/auth/signup',
        login: '/auth/login',
        logout: '/auth/logout',
        forgetPassword: '/auth/forgot-password',
        resetPassword: '/auth/reset-password',
        verifyOtp: '/auth/verify-otp',
        'refresh-token': '/auth/refresh-token',
        'verify-token': '/auth/verify-token',
    },
    Group: {
        view: '/group/view',
        create: '/group/create',
        update: '/group/update',
        patch: '/group/update',
        delete: '/group/delete',
    },
    Profile: {
        view: '/profile/view',
        create: '/profile/create',
        update: '/profile/update',
        patch: '/profile/update',
        delete: '/profile/delete',
    },
    Contact: {
        view: '/contact/view',
        create: '/contact/create',
        update: '/contact/update',
        patch: '/contact/update',
        delete: '/contact/delete',
    },
    Sources: {
        view: '/source/view',
        create: '/source/create',
        update: '/source/update',
        patch: '/source/update',
        delete: '/source/delete',
    },
    Deals: {
        view: '/deals/view',
        create: '/deals/create',
        update: '/deals/update',
        patch: '/deals/update',
        delete: '/deals/delete',
    },
    Pipeline: {
        view: '/pipeline/view',
        create: '/pipeline/create',
        update: '/pipeline/update',
        patch: '/pipeline/update',
        delete: '/pipeline/delete',
    },
    Companies: {
        view: '/company/view',
        create: '/company/create',
        update: '/company/update',
        patch: '/company/update',
        delete: '/company/delete',
    },
    Permissions: {
        view: '/permissions/view',
        create: '/permissions/create',
        update: '/permissions/update',
        patch: '/permissions/update',
        delete: '/permissions/delete',
    },
    Role: {
        view: '/role/view',
        create: '/role/create',
        update: '/role/update',
        patch: '/role/update',
        delete: '/role/delete',
    },
    Settings: {
        view: '/settings/view',
        create: '/settings/create',
        update: '/settings/update',
        patch: '/settings/update',
        delete: '/settings/delete',
    },
    Dashboard: {
        view: '/dashboard/view',
    },
}