
export const endpoints = {
    Auth: {
        signup: '/auth/signup',
        login: '/auth/login',
        logout: '/auth/logout',
        forgetPassword: '/auth/forgot-password',
        resetPassword: '/auth/reset-password',
        verifyOtp: '/auth/verify-otp',
        'refresh-token': '/auth/refresh-token',
        'verify-token': '/auth/verify-token',
    },
    Group: {
        view: '/group/view',
        create: '/group/create',
        update: '/group/update',
        patch: '/group/update',
        delete: '/group/delete',
        delete_bulk: '/group/bulk-delete',
    },
    Profile: {
        view: '/profile/view',
        me: '/profile/me',
        create: '/profile/create',
        update: '/profile/update',
        patch: '/profile/update',
        delete: '/profile/delete',
        delete_bulk: '/profile/bulk-delete',
    },
    Contact: {
        view: '/contact/view',
        sendMail: '/contact/send-mail',
        create: '/contact/create',
        update: '/contact/update',
        patch: '/contact/update',
        delete: '/contact/delete',
        delete_bulk: '/contact/bulk-delete',
    },
    Bill: {
        find: '/bill/search',
    },
    Sources: {
        view: '/source/view',
        create: '/source/create',
        update: '/source/update',
        patch: '/source/update',
        delete: '/source/delete',
        delete_bulk: '/source/bulk-delete',
    },
    Deals: {
        view: '/deals/view',
        create: '/deals/create',
        update: '/deals/update',
        patch: '/deals/update',
        delete: '/deals/delete',
        delete_bulk: '/deals/bulk-delete',
    },
    Products: {
        import: '/products/import',
        view: '/products/view',
        create: '/products/create',
        update: '/products/update',
        patch: '/products/update',
        delete: '/products/delete',
        delete_bulk: '/products/bulk-delete',
    },
    Categories: {
        view: '/category/view',
        create: '/category/create',
        update: '/category/update',
        patch: '/category/update',
        delete: '/category/delete',
        delete_bulk: '/category/bulk-delete',
    },
    SubCategory: {
        view: '/sub-category/view',
        create: '/sub-category/create',
        update: '/sub-category/update',
        patch: '/sub-category/update',
        delete: '/sub-category/delete',
        delete_bulk: '/sub-category/bulk-delete',
    },
    Types: {
        view: '/type/view',
        create: '/type/create',
        update: '/type/update',
        patch: '/type/update',
        delete: '/type/delete',
        delete_bulk: '/type/bulk-delete',
    },
    SubType: {
        view: '/sub-type/view',
        create: '/sub-type/create',
        update: '/sub-type/update',
        patch: '/sub-type/update',
        delete: '/sub-type/delete',
        delete_bulk: '/sub-type/bulk-delete',
    },
    Tax: {
        view: '/tax/view',
        create: '/tax/create',
        update: '/tax/update',
        patch: '/tax/update',
        delete: '/tax/delete',
        delete_bulk: '/tax/bulk-delete',
    },
    Pipeline: {
        view: '/pipeline/view',
        create: '/pipeline/create',
        update: '/pipeline/update',
        patch: '/pipeline/update',
        delete: '/pipeline/delete',
        delete_bulk: '/pipeline/bulk-delete',
    },
    Companies: {
        view: '/company/view',
        create: '/company/create',
        update: '/company/update',
        patch: '/company/update',
        delete: '/company/delete',
        delete_bulk: '/company/bulk-delete',
    },
    Permissions: {
        view: '/permissions/view',
        create: '/permissions/create',
        update: '/permissions/update',
        patch: '/permissions/update',
        delete: '/permissions/delete',
        delete_bulk: '/permissions/bulk-delete',
    },
    Role: {
        view: '/role/view',
        create: '/role/create',
        update: '/role/update',
        patch: '/role/update',
        delete: '/role/delete',
        delete_bulk: '/role/bulk-delete',
    },
    Settings: {
        view: '/settings/view',
        create: '/settings/create',
        update: '/settings/update',
        patch: '/settings/update',
        delete: '/settings/delete',
        delete_bulk: '/settings/bulk-delete',
    },
    Dashboard: {
        view: '/dashboard/view',
    },
}