
import { v4 as uuidv4 } from 'uuid'
import {
  TextFields, 
  SmartButton,
  FormatTextdirectionLToR,
  Link,
  CheckBox,
  ToggleOff,
  LinearScale,
  Title,
  DateRange,
  HourglassEmpty,
  RadioButtonChecked,
  Checklist
} from '@mui/icons-material'

export const templateBuilderItems = [
  {
    id: uuidv4(),
    type: "heading",
    icon: <Title />,
    title: "Heading",
    properties: {
      text: "Heading text",
      level: 1,
      fontSize: "24px",
      bold: true,
      value: "",
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "paragraph",
    icon: <FormatTextdirectionLToR />,
    title: "Paragraph",
    properties: {
      text: "Paragraph text",
      fontSize: "24px",
      bold: true,
      value: "",
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "number",
    icon: <Title />,
    title: "Number",
    properties: {
      text: "Number text",
      fontSize: "24px",
      bold: true,
      value: 0,
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "text",
    icon: <TextFields />,
    title: "Text",
    properties: {
      text: "Enter your text here",
      fontSize: "16px",
      color: "#333",
      value: "",
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "button",
    icon: <SmartButton />,
    title: "Button",
    properties: {
      label: "Click Me",
      variant: "contained",
      color: "primary",
      value: "",
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "link",
    icon: <Link />,
    title: "Link",
    properties: {
      text: "Visit site",
      href: "https://example.com",
      value: "",
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "checkbox",
    icon: <CheckBox />,
    title: "Checkbox",
    properties: {
      label: "Accept terms",
      checked: false,
      value: "",
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "radio",
    icon: <ToggleOff />,
    title: "Radio Button",
    properties: {
      label: "Option 1",
      checked: false,
      value: "",
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "checkboxGroup",
    icon: <CheckBox />,
    title: "Checkbox Group",
    properties: {
      label: "Option 1",
      options: [
        { id: uuidv4(), label: "Option 1", value: "option1" },
        { id: uuidv4(), label: "Option 2", value: "option2" },
        { id: uuidv4(), label: "Option 3", value: "option3" },
      ],
      checked: false,
      value: "",
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "radioGroup",
    icon: <RadioButtonChecked />,
    title: "Radio Group",
    properties: {
      label: "Option 1",
      checked: false,
      options: [
        { id: uuidv4(), label: "Option 1", value: "option1" },
        { id: uuidv4(), label: "Option 2", value: "option2" },
        { id: uuidv4(), label: "Option 3", value: "option3" },
      ],
      value: "",
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "select",
    icon: <Checklist />,
    title: "Select",
    properties: {
      label: "Option 1",
      checked: false,
      options: [
        { id: uuidv4(), label: "Option 1", value: "option1" },
        { id: uuidv4(), label: "Option 2", value: "option2" },
        { id: uuidv4(), label: "Option 3", value: "option3" },
      ],
      value: "",
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "slider",
    icon: <LinearScale />,
    title: "Range Selector",
    properties: {
      min: 0,
      max: 100,
      step: 5,
      value: 50,
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "date",
    icon: <DateRange />,
    title: "Date Picker",
    properties: {
      format: "YYYY-MM-DD",
      value: "",
      fullWidth: "no",
    },
  },
  {
    id: uuidv4(),
    type: "time",
    icon: <HourglassEmpty />,
    title: "Time Picker",
    properties: {
      format: "HH:mm",
      value: "",
      fullWidth: "no",
    },
  },
];